/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.login;
import Modelo.loginDAO;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public void scaleimg(){
        ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\SistemaVentas_VyaRenda\\src\\Imagenes\\login.jpg");
        Image img = icon.getImage();
        Image imgscl = img.getScaledInstance(lateral_lbl.getWidth(), lateral_lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sclit = new ImageIcon(imgscl);
        lateral_lbl.setIcon(sclit);
    }
    public Login() {
        initComponents();
        scaleimg();
    }
    public void validar(){
        String correo = correo_txt.getText();
        String pass = String.valueOf(password_txt.getPassword());
        if (!"".equals(correo) || !"".equals(pass)){
            login lg = new login();
            loginDAO login = new loginDAO();
            lg = login.log(correo, pass);
            if(lg.getCorreo() != null && lg.getPass() != null) {
                Sistema sis = new Sistema ();
                sis.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Correo o contraseña incorrectos");
                correo_txt.setText("");
                password_txt.setText("12345678");
                correo_txt.requestFocus();
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        candado_lbl = new javax.swing.JLabel();
        correo_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        correo_txt = new javax.swing.JTextField();
        iniciar_btn = new javax.swing.JButton();
        password_txt = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lateral_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        candado_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar.png"))); // NOI18N

        correo_lbl.setForeground(new java.awt.Color(0, 51, 153));
        correo_lbl.setText("Correo Electrónico");

        password_lbl.setForeground(new java.awt.Color(0, 0, 153));
        password_lbl.setText("Contraseña");

        correo_txt.setBackground(new java.awt.Color(255, 255, 255));
        correo_txt.setText("user@example.com");
        correo_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correo_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correo_txtFocusLost(evt);
            }
        });
        correo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo_txtActionPerformed(evt);
            }
        });

        iniciar_btn.setBackground(new java.awt.Color(51, 51, 51));
        iniciar_btn.setForeground(new java.awt.Color(255, 255, 255));
        iniciar_btn.setText("Iniciar Sesión");
        iniciar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_btnActionPerformed(evt);
            }
        });

        password_txt.setText("jPasswordField1");
        password_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_txtFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(correo_lbl)
                            .addComponent(correo_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(password_lbl)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(iniciar_btn))
                            .addComponent(password_txt))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(candado_lbl)
                        .addGap(141, 141, 141))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(candado_lbl)
                .addGap(33, 33, 33)
                .addComponent(correo_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(password_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(iniciar_btn)
                .addGap(73, 73, 73))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 63, 400, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 620));

        lateral_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.jpg"))); // NOI18N
        lateral_lbl.setAlignmentX(0.5F);
        lateral_lbl.setIconTextGap(0);
        getContentPane().add(lateral_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, -220, 390, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo_txtActionPerformed

    private void iniciar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_btnActionPerformed
        validar();
    }//GEN-LAST:event_iniciar_btnActionPerformed

    private void correo_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correo_txtFocusGained
       correo_txt.setText(""); 
    }//GEN-LAST:event_correo_txtFocusGained

    private void correo_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correo_txtFocusLost

    }//GEN-LAST:event_correo_txtFocusLost

    private void password_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_txtFocusGained
        password_txt.setText("");
    }//GEN-LAST:event_password_txtFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel candado_lbl;
    private javax.swing.JLabel correo_lbl;
    private javax.swing.JTextField correo_txt;
    private javax.swing.JButton iniciar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lateral_lbl;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_txt;
    // End of variables declaration//GEN-END:variables
}
